### ISSUE TITLE
The program should check that the input files does exist

### ISSUE THREAD

**Issue by bew** [marcusbuffett/pipe-rename#19]
TSIA I think!
```
$ renamer i-do-not-exist

..... [open editor, make changes] .....

The following replacements were found:

i-do-not-exist -> i-do-not-exist-foo

Execute these renames? yes
Error: No such file or directory (os error 2)
```

**Comment by Stargateur** [comment]
it does no ? What is the behavior you would expect ?

I guess an option, ignore error could be add. But this as default behavior seem right to me.

**Comment by bew** [comment]
Okay, I agree with you it isn't a good explanation of the problem _at all_ (didn't have much time when I thought about this...)

The check we see is currently at the very end (and it doesn't really look like a check, more like that the syscall to rename the file didn't work).
I get an error after I did the name changes I wanted etc.. But if the initial file name does not exist, my changes are of no use at all, and I'd have to re-make all the changes when I re-run the program with the correct file names.

I would have expected it to show an error immediately instead.

**Comment by Stargateur** [comment]
> and it doesn't really look like a check, more like that the syscall to rename the file didn't work

that the best, the OS will check anyway

**Comment by marcusbuffett** [comment]
I agree that getting an error right away would be better, it would be annoying to have a bunch of renames pending and then it errors out because you misspelled a file name when invoking the command, would be better to get an error right away. Hasn't been a problem for me in practice, since tab-completion and piping `ls` into it doesn't end up with non-existent files, but I can see it happening with other use cases, I'm in favor of this change :+1:
