### ISSUE TITLE
Check if file already exists before renaming

### ISSUE THREAD

**Issue by robinkrahl** [marcusbuffett/pipe-rename#7]
To avoid accidentally overriding files, pipe-rename should check whether a target file already exists before renaming.  This would also help to avoid a potential problem if the user selects the name of one of the input files as an output file.

**Comment by marcusbuffett** [comment]
Agreed this makes sense, I added this in b5e2df7084417324b6ecf5e046e8f52156dff2e0

**Comment by marcusbuffett** [comment]
Eh nvm, I'm reopening this because I realize my solution doesn't work for cases where something like this happens:
- a.txt -> b.txt
- c.txt -> a.txt

by the time it gets to the second replacement, `a.txt` has already been moved. I think it's better to do it in one pass before doing replacements, so I'll do that instead.

**Comment by marcusbuffett** [comment]
Alright take 2: d895c4cf50475fed15e9273a8131faae2f3d6c54
